workflows:
  android-workflow:
    name: Build APK
    instance_type: mac_mini_m1
    environment:
      groups:
        - name: default
      vars:
        PACKAGE_NAME: "com.example.sniperlog"
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - fandysecure02@gmail.com
        notify:
          success: true
          failure: true
